### ISSUE TITLE
Plugin sends again the last state of button when deployed

### ISSUE THREAD

**Issue by S474N** [Mimiix/node-red-contrib-deconz#85] opened 2020-08-09 18:08 UTC
** Describe issue **
Have Aqara Switch (WXKG11LM) in Phoscon. This button is represented as "ZHASwitch" in Nodered. 

If I press button 1x, then will node report:` {"ProgrammableSwitchEvent":0,"ServiceLabelIndex":1}`

If twice then node report: ` {"ProgrammableSwitchEvent":1,"ServiceLabelIndex":1}`

Don't know why, but plugin holds last state of this stateless button. If the last state is one click, and the light is off (because for example 60s timeout) and I make new full Deploy, then will be again send `"ProgrammableSwitchEvent":0,"ServiceLabelIndex":1}` and the light will turn on. If the last state before deploying is PSE:1, then again this state is send after deploying.

** Your flow here **
Not necessary, status is reported directly from node.  

** Screens / Logs **
![AAAAAElFTkSuQmCC](https://user-images.githubusercontent.com/16512337/89738579-2e8bca80-da7a-11ea-88f1-82251a40bc6b.png)

** Hardware / Software **

-  raspberry 4

- version of deconz gateway: [2.05.78 / 22/05/2020]

-  version of node-red-contrib-deconz: 1.2.0

**Comment by mattmattmatt** [comment] 2020-08-14 08:38
I have the same issue, and it seems related to `sendLastState` calling `sendStateHomekitOnly` whenever the node gets redeployed. 

Is the best practice _not_ to use the second node output (the one with the `ProgrammableSwitchEvent`), but instead the first output (with e.g. `buttonevent: 1000`) for manual automations?

**Comment by S474N** [comment] 2020-08-14 11:29
Tested with this script from first output and the same problem :(

```
const input = msg.payload;

var press1x = { payload: {"ProgrammableSwitchEvent": 0, "ServiceLabelIndex": 1 }};
var press2x = { payload: {"ProgrammableSwitchEvent": 1, "ServiceLabelIndex": 1 }};
var press3x = { payload: {"ProgrammableSwitchEvent": 3, "ServiceLabelIndex": 1 }};
var press4x = { payload: {"ProgrammableSwitchEvent": 4, "ServiceLabelIndex": 1 }};

if(input.buttonevent !== undefined){
    switch(input.buttonevent){
        case 1002: return press1x;
        case 1004: return press2x;
        case 1005: return press3x;
        case 1006: return press4x;
        default:
            node.warn('Unknown button code.');
            return;
    }
}
return;

```

But good is that my button have 4 state. I thought, that only 2 :))

**Comment by TheNON75** [comment] 2020-08-20 01:23
Same issue here
After deploy, the output 2 (homekit payload) is sending the last status.
I am controlling speaker volume and toggle play pause also in the baby’s room, so I find it “unhealthy”..
For output 1 it can be turned off, but not for output 2

Thanks for the resolution in advance

**Comment by S474N** [comment] 2020-08-20 06:32
@TheNON75 have same problem on output1. Can you please test it? Or how you tested it?

**Comment by TheNON75** [comment] 2020-08-20 08:02
no, I did not say it is with output 1 I said it is with output 2

**Comment by S474N** [comment] 2020-08-20 17:37
I had this problem with output 2, then tested with script also output 1. It's same :(

**Comment by andreypopov** [comment] 2020-08-21 08:32
please, test 1.2.1

**Comment by TheNON75** [comment] 2020-10-25 18:56
@S474N, then what if marking to closed?

**Comment by S474N** [comment] 2020-10-28 09:06
There is only version 1.2.0 in nodered palette.

**Comment by TheNON75** [comment] 2020-10-28 13:26
Yes, but you confirmed the solution works,  therefore you should close it to let it go in my opninion. Or contact the maintainer

**Comment by S474N** [comment] 2020-10-28 13:44
Will wait for final version oof 1.2.1 to check it ;)

**Comment by Zehir** [comment] 2021-02-17 17:20
There is a 30 min delay between the version seen on https://flows.nodered.org/node/node-red-contrib-deconz and in manage palette settings.

**Comment by Zehir** [comment] 2021-02-17 17:21
If your issue is not resolved please open it again but it's seems to be ok.

**Closed** 2021-02-17 17:20 UTC
Labels: bug

**Comment by gsieben** [comment] 2021-12-07 12:06
Updated to Version 2.1.3... the problem is back again

**Comment by Zehir** [comment] 2021-12-07 14:42
> Updated to Version 2.1.3... the problem is back again

Please open à New issue
