### ISSUE TITLE
Set a device by input

### ISSUE THREAD

**Issue by nicedevil007** [Mimiix/node-red-contrib-deconz#47] opened 2019-12-21 23:37 UTC
Hey andrey,

would it be possible to configure your nodes this way that they can switch between devices on msg.topic or anything else?

f.e. I have a living room light and one for the kitchen. Now I have to make 2 Nodes for those instead of just 1.

I coded a button logic for IKEA Tradfri switches. This logic is inside a Subflow. All I have to do is putting a msg.buttonevent inside my subflow and then the magic happens :)

The output will then be sended through a switch node to split everything up to the right light instead of just putting one deconz-out node behind this subflow (or even inside).

**Comment by Zehir** [comment] 2021-02-17 18:22
Duplicate of #91

**Closed by Zehir** 2021-02-17 18:22 UTC
Labels: duplicate, improvement
