### ISSUE TITLE
Set device by name or id instead off select box

### ISSUE THREAD

**Issue by NEijsink** [Mimiix/node-red-contrib-deconz#45] opened 2019-12-12 11:47 UTC
Is it possible to set the device by the msg.payload or msg.topic, rather than selecting a device within the node settings? So that you are able to switch multiple devices by a single function node for example.

**Comment by Zehir** [comment] 2021-02-17 18:28
Duplicate of #91

**Closed by Zehir** 2021-02-17 18:28 UTC
Labels: improvement
